[Metadata]

# Full name of the mod, without version number
Name = The Vault

# Author name or nick, don't use email address
Author = Josh Clue

Version = VERSION

# Short description of the mod, main goals, features etc
Description = A classic quest and item mod for Baldur's Gate. It adds new encounters, mysterious plots, and improvement combat to the campaign, including item upgrades forgeable by Taerom in Beregost. 
Modernized by the community (erebustan, Beleg33, K4thos, Ikki, Roxanne) for compatibility with BG:EE, BGT, and EET 

# Web address of mod Homepage
Homepage = https://mods.shsforums.net/

#  Web address of mod dedicated forum or forum thread 
Forum = https://www.gibberlings3.net/

# if you use Github.com (preferred hosting site), simply use github.com/AccountOrOrgName/RepositoryName    
# If you use other hosting sites, please check requirements and put direct download link  
Download = https://github.com/Spellhold-Studios/Vault

# Type of LABELs used by the mod, read more here https://www.gibberlings3.net/forums/topic/32516-tutorial-what-is-label
LabelType = GloballyUnique

# Dynamic Install Order Category
Type = Quest

ModuleType = BGEE, EET

Before = Item Revisions, EET_end

After = EET, NTOTSC